<?xml version="1.0"?>
<package format="3">
  <name>admittance_control_ros2</name>
  <version>0.2.0</version>
  <description>Admittance control borné pour UR5e avec Bota HEX-E ou capteur F/T interne.</description>
  <maintainer email="mohamedalijomaaghouil@gmail.com">Mohamed Ali</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>urdf</depend>
  <depend>kdl_parser</depend>
  <depend>orocos_kdl</depend>
  <depend>eigen</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
