<?xml version="1.0"?>
<package format="3">
  <name>robota_sudoe_imitation</name>
  <version>0.1.0</version>
  <description>Traitement des démonstrations pour apprentissage par imitation.</description>
  <maintainer email="mohamedalijomaaghouil@gmail.com">Mohamed Ali</maintainer>
  <license>BSD</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <export><build_type>ament_python</build_type></export>
</package>
